"""ValueSet: ActClass.

https://terminology.hl7.org/5.2.0/ValueSet-v3-ActClass.html
"""

from enum import StrEnum


class ActClass(StrEnum):
    """ValueSet: ActClass.

    https://terminology.hl7.org/5.2.0/ValueSet-v3-ActClass.html
    """

    ACT = "ACT"
    _ActClassRecordOrganizer = "_ActClassRecordOrganizer"
    COMPOSITION = "COMPOSITION"
    DOC = "DOC"
    DOCCLIN = "DOCCLIN"
    CDAVLONE = "CDAVLONE"
    CONTAINER = "CONTAINER"
    CATEGORY = "CATEGORY"
    DOCBODY = "DOCBODY"
    DOCSECT = "DOCSECT"
    TOPIC = "TOPIC"
    EXTRACT = "EXTRACT"
    EHR = "EHR"
    FOLDER = "FOLDER"
    GROUPER = "GROUPER"
    CLUSTER = "CLUSTER"
    ACCM = "ACCM"
    ACCT = "ACCT"
    ACSN = "ACSN"
    ADJUD = "ADJUD"
    CACT = "CACT"
    ACTN = "ACTN"
    INFO = "INFO"
    STC = "STC"
    CNTRCT = "CNTRCT"
    FCNTRCT = "FCNTRCT"
    COV = "COV"
    CONC = "CONC"
    HCASE = "HCASE"
    OUTBR = "OUTBR"
    CONS = "CONS"
    CONTREG = "CONTREG"
    CTTEVENT = "CTTEVENT"
    DISPACT = "DISPACT"
    EXPOS = "EXPOS"
    AEXPOS = "AEXPOS"
    TEXPOS = "TEXPOS"
    INC = "INC"
    INFRM = "INFRM"
    INVE = "INVE"
    LIST = "LIST"
    MPROT = "MPROT"
    OBS = "OBS"
    _ActClassROI = "_ActClassROI"
    ROIBND = "ROIBND"
    ROIOVL = "ROIOVL"
    _SubjectPhysicalPosition = "_SubjectPhysicalPosition"
    _SubjectBodyPosition = "_SubjectBodyPosition"
    LLD = "LLD"
    PRN = "PRN"
    RLD = "RLD"
    SFWL = "SFWL"
    SIT = "SIT"
    STN = "STN"
    SUP = "SUP"
    RTRD = "RTRD"
    TRD = "TRD"
    _ImagingSubjectOrientation = "_ImagingSubjectOrientation"
    ALRT = "ALRT"
    BATTERY = "BATTERY"
    CLNTRL = "CLNTRL"
    CNOD = "CNOD"
    COND = "COND"
    CASE = "CASE"
    OUTB = "OUTB"
    DGIMB = "DGIMB"
    GEN = "GEN"
    DETPOL = "DETPOL"
    EXP = "EXP"
    LOC = "LOC"
    PHN = "PHN"
    POL = "POL"
    SEQ = "SEQ"
    SEQVAR = "SEQVAR"
    INVSTG = "INVSTG"
    OBSSER = "OBSSER"
    OBSCOR = "OBSCOR"
    POS = "POS"
    POSACC = "POSACC"
    POSCOORD = "POSCOORD"
    SPCOBS = "SPCOBS"
    VERIF = "VERIF"
    PCRP = "PCRP"
    ENC = "ENC"
    POLICY = "POLICY"
    JURISPOL = "JURISPOL"
    ORGPOL = "ORGPOL"
    SCOPOL = "SCOPOL"
    STDPOL = "STDPOL"
    PROC = "PROC"
    SBADM = "SBADM"
    SBEXT = "SBEXT"
    SPECCOLLECT = "SPECCOLLECT"
    REG = "REG"
    REV = "REV"
    SPCTRT = "SPCTRT"
    SPLY = "SPLY"
    DIET = "DIET"
    STORE = "STORE"
    SUBST = "SUBST"
    TRFR = "TRFR"
    TRNS = "TRNS"
    XACT = "XACT"
    _ActClassContainer = "_ActClassContainer"
    ENTRY = "ENTRY"
    ORGANIZER = "ORGANIZER"
    _ActContainer = "_ActContainer"
    DOCCNTNT = "DOCCNTNT"
    DOCLIST = "DOCLIST"
    DOCLSTITM = "DOCLSTITM"
    DOCPARA = "DOCPARA"
    DOCTBL = "DOCTBL"
    LINKHTML = "LINKHTML"
    LOCALATTR = "LOCALATTR"
    LOCALMRKP = "LOCALMRKP"
    ordered = "ordered"
    REFR = "REFR"
    TBLCOL = "TBLCOL"
    TBLCOLGP = "TBLCOLGP"
    TBLDATA = "TBLDATA"
    TBLHDR = "TBLHDR"
    TBLROW = "TBLROW"
    tbody = "tbody"
    tfoot = "tfoot"
    thead = "thead"
    unordered = "unordered"
